[package]
name = "msfmt"
version = "0.2.0"
authors = ["Vincent Parizet <vincent.parizet@hotmail.fr>"]
edition = "2018"

[dependencies]
lib_maniascript = { path = "../lib_maniascript" }
clap = "2.33.0"