[package]
name = "lib_macros"
version = "0.1.0"
authors = ["Vincent Parizet <vincent.parizet@hotmail.fr>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0.1", features = ["extra-traits"] }
quote = "1.0.0"
